In [20]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [21]:
import numpy as np
import pandas as pd

In [22]:
a = [1,2,3,4,5,6]

In [23]:
s = pd.Series(a)

In [24]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [25]:
d = {"Aman":68,"rohan":34,"Akarsh":89}
s = pd.Series(d)

In [26]:
s

Aman      68
rohan     34
Akarsh    89
dtype: int64

In [27]:
pd.DataFrame({
    "name": ["Aman", "Riya"],
    "salary": [40000, 65000]
})

   name  salary
0  Aman   40000
1  Riya   65000

In [28]:
df = pd.read_csv("employees_100.csv")

In [29]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [30]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [31]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [32]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
80,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07

In [33]:
df.shape

(100, 10)

In [34]:
df.dtypes

employee_id             int64
name                   object
department             object
city                   object
age                   float64
salary                 object
experience              int64
performance_score       int64
projects_completed      int64
joining_date           object
dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    object
 2   department          92 non-null     object
 3   city                90 non-null     object
 4   age                 94 non-null     float64
 5   salary              92 non-null     object
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    object
dtypes: float64(1), int64(4), object(5)
memory usage: 7.9+ KB

In [36]:
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [37]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [38]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [39]:
df[["name",'salary']].head()

             name salary
0    Swati Kapoor  70719
1  Kavya Malhotra  77058
2    Manish Desai  69911
3        Neha Das  69993
4       Isha Nair  88216

In [40]:
df = df.set_index("employee_id")

In [41]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [42]:
df.loc[184:145]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [43]:
df.iloc[0:10]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
181,Karan Rao,Marketing,NaN,22.0,50733,1,6,6,2020-04-05
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
101,Ananya Malhotra,engineering,NaN,24.0,68591,2,8,0,2023-10-21

In [44]:
df.iloc[1:5][["name","city","age","salary"]]

                       name       city   age salary
employee_id
154          Kavya Malhotra     Mumbai   NaN  77058
171            Manish Desai  Hyderabad  23.0  69911
146                Neha Das       Pune  28.0  69993
145               Isha Nair        NaN  32.0  88216

In [45]:
df[df['age'] > 40]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [46]:
#give me people who re working in finance and there age is greater than 30

In [47]:
df[((df['department'] == "Finance") | (df['department'] == "Sales")) & (df['age'] > 30) & (df['experience'] > 5)]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
143,Neha Rao,Sales,Hyderabad,37.0,NaN,11,6,11,2023-05-15
182,Pooja Reddy,Sales,Delhi,34.0,63700,7,6,14,2019-12-28
179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
137,Ritu Bose,Finance,Bangalore,38.0,71062,8,6,4,2023-12-19
176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
195,Pooja Nair,Finance,NaN,33.0,69396,6,6,4,2023-01-13
138,Rahul Gupta,Finance,Hyderabad,35.0,"75,614",11,7,14,2020-10-18
103,Ananya Nayak,Sales,Delhi,38.0,68490,9,6,6,2021-11-19

In [48]:
df[df["department"].isin(["Engineering", "Data Science"])]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
111,Kavya Singh,Engineering,Delhi,23.0,NaN,1,5,10,2021-09-14
105,Vivek Pillai,Engineering,Pune,39.0,NaN,9,4,5,2024-06-05
132,Swati Malhotra,Engineering,Chennai,33.0,77222,5,7,15,2018-10-09
156,Aditya Kapoor,Data Science,Kolkata,26.0,69765,0,2,4,2020-04-12
127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
170,Rahul Nair,Data Science,Kolkata,30.0,76425,5,2,4,2021-06-25
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
148,Kavya Nair,Engineering,Chennai,NaN,"76,320",3,7,11,2024-03-07
194,Pooja Menon,Engineering,Chennai,NaN,76281,7,4,9,2022-07-28
108,Ananya Rao,Engineering,Pune,38.0,78545,6,5,10,2022-02-16
109,Rohan Kulkarni,Data Science,Delhi,28.0,76267,5,6,3,2023-01-24
190,Swati Bose,Data Science,Mumbai,22.0,78465,0,8,18,2022-11-22
157,Ananya Rao,Engineering,Mumbai,25.0,NaN,2,5,8,2022-04-07
144,Arjun Nayak,Engineering,Kolkata,38.0,75226,7,6,17,2019-12-27
168,Sanjay Kulkarni,Engineering,Delhi,34.0,80358,7,5,14,2020-04-01
147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
102,Rahul Menon,Engineering,Hyderabad,38.0,84870,11,6,15,2021-06-07
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
187,Aditya Bose,Engineering,Bangalore,36.0,81112,7,4,9,2022-03-26
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05

In [49]:
df[df["name"].str.contains("Verma")]

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
127,Suresh Verma,Data Science,Bangalore,27.0,"72,862",2,6,10,2023-02-21
116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17
110,Arjun Verma,Marketing,Pune,29.0,62227,4,7,8,2022-04-05
151,Sneha Verma,Finance,Delhi,NaN,66422,5,6,5,2023-09-02
147,Tanvi Verma,Engineering,Bangalore,35.0,77217,8,3,0,2022-04-22
133,Riya Verma,HR,Kolkata,26.0,59693,3,6,20,2024-05-08
124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
188,Sanjay Verma,HR,Bangalore,33.0,59591,8,4,4,2019-03-05
192,Divya Verma,HR,Delhi,40.0,66363,12,7,13,2022-09-10

In [50]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [51]:
df.dropna(subset = ['city',"age"])

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
140,Rahul Gupta,Sales,Hyderabad,23.0,52404,0,9,13,2018-12-27
123,Sneha Iyer,HR,Hyderabad,33.0,59895,4,4,18,2024-02-21
...,...,...,...,...,...,...,...,...,...
121,Ashok Shah,Data Science,Pune,31.0,75498,4,7,7,2024-12-05
161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [52]:
df.head()

,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
employee_id,,,,,,,,,
184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [53]:
df['age'].fillna(df['age'].mean(),inplace = True)

/tmp/ipykernel_2159/240904280.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace = True)

In [54]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [55]:
df['salary'] = df['salary'].str.replace(",", "", regex=False)
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')
df['salary'] = df['salary'].fillna(df['salary'].median())

In [56]:
df['salary'].dtype

dtype('float64')

In [57]:
df.isnull().sum()

name                   0
department             8
city                  10
age                    0
salary                 0
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [58]:
df['department'].value_counts()

department
HR              17
Marketing       17
Finance         16
Engineering     14
Data Science    10
Sales            8
engineering      3
 HR              2
 Marketing       1
 Finance         1
FINANCE          1
SALES            1
MARKETING        1
Name: count, dtype: int64

In [59]:
df['department'] = df['department'].fillna(df['department'].mode()[0])

In [60]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [61]:
df.isnull().sum()

name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [62]:
df.duplicated().sum()

np.int64(0)

In [63]:
df = df.reset_index()

In [64]:
df.duplicated(subset=["employee_id"]).sum()

np.int64(4)

In [65]:
df.drop_duplicates(subset=["employee_id"], keep="first", inplace = True)

In [66]:
df["joining_date"] = pd.to_datetime(df["joining_date"])

In [67]:
df['annual_salary'] = df['salary'] * 12

In [68]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0

In [69]:
def categorize(num):
  if num > 5:
    return "Experienced candidate"
  elif num <= 5:
    return "Learner"

In [70]:
df['experience_status'] = df['experience'].apply(categorize)

In [71]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0,Learner
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Learner
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0,Learner
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0,Learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate

In [72]:
df.sort_values(by = "salary",ascending=False)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
74,158,Tanvi Malhotra,HR,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experienced candidate
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experienced candidate
39,117,Pooja Malhotra,engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Learner
...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,608796.0,Learner
67,169,Swati Chatterjee,HR,Pune,33.0,49801.0,3,6,11,2021-08-20,597612.0,Learner
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,596316.0,Learner
36,167,Meera Malhotra,HR,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,585864.0,Learner
26,141,Manish Kulkarni,HR,Chennai,27.0,45835.0,3,8,13,2022-07-21,550020.0,Learner

In [73]:
result = df.sort_values(by = ['department','salary'],ascending=[True, False])
result

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
16,177,Vivek Malhotra,Finance,Bangalore,30.861702,62969.5,3,4,12,2021-09-12,755634.0,Learner
27,162,Suresh Chatterjee,HR,Hyderabad,32.000000,59273.0,5,6,11,2020-09-05,711276.0,Learner
11,131,Priya Malhotra,Marketing,Hyderabad,25.000000,55295.0,1,7,12,2022-02-13,663540.0,Learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.000000,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate
...,...,...,...,...,...,...,...,...,...,...,...,...
38,136,Sanjay Mehta,Sales,Hyderabad,30.000000,52573.0,5,7,8,2021-02-12,630876.0,Learner
5,140,Rahul Gupta,Sales,Hyderabad,23.000000,52404.0,0,9,13,2018-12-27,628848.0,Learner
39,117,Pooja Malhotra,engineering,Kolkata,24.000000,84255.0,1,8,19,2021-12-05,1011060.0,Learner
1,154,Kavya Malhotra,engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Learner
9,101,Ananya Malhotra,engineering,Hyderabad,24.000000,68591.0,2,8,0,2023-10-21,823092.0,Learner

In [74]:
df['department'].unique()

array(['Data Science', 'engineering', 'Engineering', 'Sales', 'HR',
       'Marketing', ' Marketing ', 'Finance', ' Finance ', ' HR ',
       'FINANCE', 'SALES', 'MARKETING'], dtype=object)

In [75]:
df['department'] = df['department'].str.strip().str.title()

In [76]:
df['department'].unique()

array(['Data Science', 'Engineering', 'Sales', 'Hr', 'Marketing',
       'Finance'], dtype=object)

In [77]:
result = df.sort_values(by = ['department','salary'],ascending=[True, False])
result

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate
59,190,Swati Bose,Data Science,Mumbai,22.0,78465.0,0,8,18,2022-11-22,941580.0,Learner
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,917100.0,Learner
54,109,Rohan Kulkarni,Data Science,Delhi,28.0,76267.0,5,6,3,2023-01-24,915204.0,Learner
...,...,...,...,...,...,...,...,...,...,...,...,...
48,163,Rahul Chatterjee,Sales,Kolkata,25.0,60015.0,0,8,9,2023-05-10,720180.0,Learner
17,178,Vikram Kapoor,Sales,Chennai,29.0,57858.0,3,7,1,2020-06-26,694296.0,Learner
44,128,Rohan Chatterjee,Sales,Mumbai,26.0,52862.0,1,3,7,2022-08-04,634344.0,Learner
38,136,Sanjay Mehta,Sales,Hyderabad,30.0,52573.0,5,7,8,2021-02-12,630876.0,Learner
5,140,Rahul Gupta,Sales,Hyderabad,23.0,52404.0,0,9,13,2018-12-27,628848.0,Learner

In [78]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0,Learner
1,154,Kavya Malhotra,Engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Learner
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0,Learner
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0,Learner
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate
...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,Marketing,Chennai,22.000000,55740.0,0,5,22,2020-04-22,668880.0,Learner
96,172,Neha Desai,Hr,Chennai,22.000000,52250.0,0,5,7,2020-11-14,627000.0,Learner
97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06,755634.0,Experienced candidate
98,193,Priya Nayak,Hr,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07,681852.0,Learner
99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25,833988.0,Experienced candidate

In [79]:
df["salary_rank"] = df["salary"].rank(ascending=False)

In [80]:
df.sort_values(by = "salary_rank")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experienced candidate,1.0
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,2.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,3.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,4.0
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Learner,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,181,Karan Rao,Marketing,Hyderabad,22.0,50733.0,1,6,6,2020-04-05,608796.0,Learner,92.0
67,169,Swati Chatterjee,Hr,Pune,33.0,49801.0,3,6,11,2021-08-20,597612.0,Learner,93.0
33,129,Ashok Gupta,Marketing,Hyderabad,22.0,49693.0,0,4,7,2018-08-27,596316.0,Learner,94.0
36,167,Meera Malhotra,Hr,Hyderabad,31.0,48822.0,4,5,4,2022-06-24,585864.0,Learner,95.0
26,141,Manish Kulkarni,Hr,Chennai,27.0,45835.0,3,8,13,2022-07-21,550020.0,Learner,96.0

In [81]:
df.nlargest(5, "salary")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
74,158,Tanvi Malhotra,Hr,Mumbai,32.0,88366.0,11,5,19,2021-02-26,1060392.0,Experienced candidate,1.0
4,145,Isha Nair,Data Science,Hyderabad,32.0,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,2.0
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380.0,9,7,8,2024-06-05,1036560.0,Experienced candidate,3.0
84,102,Rahul Menon,Engineering,Hyderabad,38.0,84870.0,11,6,15,2021-06-07,1018440.0,Experienced candidate,4.0
39,117,Pooja Malhotra,Engineering,Kolkata,24.0,84255.0,1,8,19,2021-12-05,1011060.0,Learner,5.0

In [82]:
df.nsmallest(5, "performance_score")

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
20,156,Aditya Kapoor,Data Science,Kolkata,26.0,69765.0,0,2,4,2020-04-12,837180.0,Learner,29.0
24,170,Rahul Nair,Data Science,Kolkata,30.0,76425.0,5,2,4,2021-06-25,917100.0,Learner,14.0
50,125,Sneha Bose,Marketing,Mumbai,32.0,56627.0,7,2,9,2023-07-12,679524.0,Experienced candidate,77.0
76,176,Shreya Menon,Finance,Hyderabad,41.0,80597.0,9,2,18,2024-11-09,967164.0,Experienced candidate,7.0
12,174,Divya Chatterjee,Finance,Kolkata,24.0,58374.0,1,3,12,2018-09-21,700488.0,Learner,71.0

In [83]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02,848628.0,Learner,26.0
1,154,Kavya Malhotra,Engineering,Mumbai,30.861702,77058.0,1,8,8,2024-02-05,924696.0,Learner,13.0
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24,838932.0,Learner,28.0
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13,839916.0,Learner,27.0
4,145,Isha Nair,Data Science,Hyderabad,32.000000,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,Marketing,Chennai,22.000000,55740.0,0,5,22,2020-04-22,668880.0,Learner,82.0
96,172,Neha Desai,Hr,Chennai,22.000000,52250.0,0,5,7,2020-11-14,627000.0,Learner,90.0
97,115,Neha Reddy,Marketing,Chennai,43.000000,62969.5,12,4,10,2019-06-06,755634.0,Experienced candidate,48.5
98,193,Priya Nayak,Hr,Hyderabad,23.000000,56821.0,3,9,16,2019-08-07,681852.0,Learner,76.0
99,152,Kavya Joshi,Marketing,Delhi,44.000000,69499.0,10,7,4,2022-03-25,833988.0,Experienced candidate,30.0

In [94]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date,annual_salary,experience_status,salary_rank
0,184,Swati Kapoor,Data Science,Kolkata,38,70719.0,5,5,6,2021-07-02,848628.0,Learner,26.0
1,154,Kavya Malhotra,Engineering,Mumbai,30,77058.0,1,8,8,2024-02-05,924696.0,Learner,13.0
2,171,Manish Desai,Data Science,Hyderabad,23,69911.0,0,6,18,2019-04-24,838932.0,Learner,28.0
3,146,Neha Das,Engineering,Pune,28,69993.0,3,8,1,2022-12-13,839916.0,Learner,27.0
4,145,Isha Nair,Data Science,Hyderabad,32,88216.0,8,8,14,2019-11-25,1058592.0,Experienced candidate,2.0

In [93]:
df['age'] = df['age'].astype(int)

In [95]:
df['city'].unique()

array(['Kolkata', 'Mumbai', 'Hyderabad', 'Pune', 'Delhi', 'Bangalore',
       'Chennai'], dtype=object)

In [96]:
df['salary'].nunique()

89

In [99]:
df.groupby("city")['salary'].max()

city
Bangalore    81112.0
Chennai      77222.0
Delhi        80358.0
Hyderabad    88216.0
Kolkata      84255.0
Mumbai       88366.0
Pune         78545.0
Name: salary, dtype: float64

In [102]:
df.groupby(['department','city'])['salary'].mean()

department    city
Data Science  Bangalore    72862.000000
              Delhi        76267.000000
              Hyderabad    81502.333333
              Kolkata      72303.000000
              Mumbai       78465.000000
              Pune         75498.000000
Engineering   Bangalore    79164.500000
              Chennai      73129.000000
              Delhi        71663.750000
              Hyderabad    76730.500000
              Kolkata      79740.500000
              Mumbai       70013.750000
              Pune         70502.500000
Finance       Bangalore    67015.750000
              Chennai      71889.000000
              Delhi        66422.000000
              Hyderabad    69947.071429
              Kolkata      58857.666667
              Mumbai       64112.000000
              Pune         61267.000000
Hr            Bangalore    67048.000000
              Chennai      49042.500000
              Delhi        58917.600000
              Hyderabad    58083.285714
              Kolkata      55542.000000
              Mumbai       88366.000000
              Pune         59159.000000
Marketing     Bangalore    62080.666667
              Chennai      59354.750000
              Delhi        62910.000000
              Hyderabad    55663.400000
              Kolkata      59186.000000
              Mumbai       61513.500000
              Pune         58481.000000
Sales         Chennai      57858.000000
              Delhi        66095.000000
              Hyderabad    57669.125000
              Kolkata      60015.000000
              Mumbai       52862.000000
Name: salary, dtype: float64

In [103]:
df.groupby("department")[["salary", "performance_score"]].mean()  # multiple columns at once

                    salary  performance_score
department
Data Science  76450.800000           5.700000
Engineering   74038.205882           5.705882
Finance       66187.705882           5.294118
Hr            59524.875000           5.708333
Marketing     59382.000000           5.894737
Sales         59289.055556           6.555556

In [104]:
df.groupby("department").agg({
    "salary": ["mean", "max"],
    "performance_score": "mean",
    "employee_id": "count"
})

                    salary          performance_score employee_id
                      mean      max              mean       count
department
Data Science  76450.800000  88216.0          5.700000          10
Engineering   74038.205882  84870.0          5.705882          17
Finance       66187.705882  80597.0          5.294118          17
Hr            59524.875000  88366.0          5.708333          24
Marketing     59382.000000  69499.0          5.894737          19
Sales         59289.055556  68490.0          6.555556           9

In [105]:
department_summary = df.groupby("department").agg(
    average_salary=("salary", "mean"),
    highest_salary=("salary", "max"),
    employee_count=("employee_id", "count")
)

In [107]:
department_summary

              average_salary  highest_salary  employee_count
department
Data Science    76450.800000         88216.0              10
Engineering     74038.205882         84870.0              17
Finance         66187.705882         80597.0              17
Hr              59524.875000         88366.0              24
Marketing       59382.000000         69499.0              19
Sales           59289.055556         68490.0               9